package com.eastnets.test.helper;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;

import com.eastnets.domain.admin.ApprovalStatus;
import com.eastnets.domain.admin.Profile;
import com.eastnets.domain.admin.User;
import com.eastnets.service.admin.AdminService;

import enReporting.test.base.BaseAppTest;

public class AdminUtility extends BaseAppTest {

	static AdminService adminService;

	@PostConstruct
	public void init() {

		adminService = (AdminService) getContext().getBean("adminService");
	}

	public static Profile createProfile(String name, String desc, Long groupID, long approvalStatus) {

		Profile profile = new Profile();
		profile.setName(name);
		if (groupID != null)
			profile.setGroupId(groupID);

		if (desc != null)
			profile.setDescription(desc);

		List<String> roles = new ArrayList<>();
		roles.add("role1");
		roles.add("role2");
		roles.add("role3");

		profile.setProfileRoles(roles);

		ApprovalStatus status = new ApprovalStatus();
		status.setId(approvalStatus);

		profile.setApprovalStatus(status);

		return profile;
	}

	public static User createUser(Long userID, String username, String password, Integer authenticationMethod,
			Long approvalStatusID) {

		ApprovalStatus approvalStatus = new ApprovalStatus();
		approvalStatus.setId(approvalStatusID);

		User user = new User();

		user.setUserId(userID);
		user.setUserName(username);
		user.setPassword(password);
		user.setAuthenticationMethod(authenticationMethod);
		user.setApprovalStatus(approvalStatus);
		user.setAutoGeneratedPassword(false);
		user.setCreateOnDatabase(true);
		user.setProfile(getSuperProfile());

		return user;
	}

	public static Profile getSuperProfile() {

		return adminService.getProfile("side", "super");

	}

}
