package com.eastnets.service.common;

public enum PasswordChangeStatus {
	SUCCESS, FAIL, EMPTY, SHORT, LONG, CONTAIN_USERNAME, CONTAIN_REVERSE_USERNAME, CONTAIN_USERNAME_PART, CONTAIN_SPACE, NOT_CONTAIN_UPPER, NOT_CONTAIN_LOWER, NOT_CONTAIN_NUMBER, INVALID_CHAR, NOT_CONTAIN_SPERCIAL_CHAR, USER_NOT_FOUND, AUTHENTICATOR_NOT_FOUND, NOT_START_ALPHA, PASSWORD_USED_BEFORE
}



