package com.eastnets.domain.admin;

public enum SaveUserEnum {
	DB_USER_EXISTS, USER_MAIL_REQUIRED, INVALID_EMAIL_ADDRESS, SELECT_A_DATE_AFTER_TODAY, SELECT_USER_PROFILE, REPORTING_USER, DB_USER_WITH_AUTOGENERATE_PASSWORD, DB_USER;
}
