//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="BIC12" type="{urn:swift:saa:xsd:saa.2.0}BIC12"/&gt;
 *           &lt;element name="DN" type="{urn:swift:saa:xsd:saa.2.0}DN"/&gt;
 *           &lt;element name="Nickname" type="{urn:swift:saa:xsd:saa.2.0}Nickname"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="FullName" type="{urn:swift:saa:xsd:saa.2.0}AddressFullName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressInfo", propOrder = {
    "bic12",
    "dn",
    "nickname",
    "fullName"
})
public class AddressInfo {

    @XmlElement(name = "BIC12")
    protected String bic12;
    @XmlElement(name = "DN")
    protected String dn;
    @XmlElement(name = "Nickname")
    protected String nickname;
    @XmlElement(name = "FullName")
    protected AddressFullName fullName;

    /**
     * Gets the value of the bic12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC12() {
        return bic12;
    }

    /**
     * Sets the value of the bic12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC12(String value) {
        this.bic12 = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDN() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDN(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the nickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * Sets the value of the nickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNickname(String value) {
        this.nickname = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link AddressFullName }
     *     
     */
    public AddressFullName getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressFullName }
     *     
     */
    public void setFullName(AddressFullName value) {
        this.fullName = value;
    }

}
