//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressFullName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressFullName"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="X1" type="{urn:swift:saa:xsd:saa.2.0}X1"/&gt;
 *         &lt;element name="X2" type="{urn:swift:saa:xsd:saa.2.0}X2" minOccurs="0"/&gt;
 *         &lt;element name="X3" type="{urn:swift:saa:xsd:saa.2.0}X3" minOccurs="0"/&gt;
 *         &lt;element name="X4" type="{urn:swift:saa:xsd:saa.2.0}X4" minOccurs="0"/&gt;
 *         &lt;element name="FinancialInstitution" type="{urn:swift:saa:xsd:saa.2.0}FinancialInstitution" minOccurs="0"/&gt;
 *         &lt;element name="BranchInformation" type="{urn:swift:saa:xsd:saa.2.0}BranchInformation" minOccurs="0"/&gt;
 *         &lt;element name="CityName" type="{urn:swift:saa:xsd:saa.2.0}CityName" minOccurs="0"/&gt;
 *         &lt;element name="Location" type="{urn:swift:saa:xsd:saa.2.0}Location" minOccurs="0"/&gt;
 *         &lt;element name="CountryCode" type="{urn:swift:saa:xsd:saa.2.0}Countrycode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressFullName", propOrder = {
    "x1",
    "x2",
    "x3",
    "x4",
    "financialInstitution",
    "branchInformation",
    "cityName",
    "location",
    "countryCode"
})
public class AddressFullName {

    @XmlElement(name = "X1", required = true)
    protected String x1;
    @XmlElement(name = "X2")
    protected String x2;
    @XmlElement(name = "X3")
    protected String x3;
    @XmlElement(name = "X4")
    protected String x4;
    @XmlElement(name = "FinancialInstitution")
    protected String financialInstitution;
    @XmlElement(name = "BranchInformation")
    protected String branchInformation;
    @XmlElement(name = "CityName")
    protected String cityName;
    @XmlElement(name = "Location")
    protected String location;
    @XmlElement(name = "CountryCode")
    protected String countryCode;

    /**
     * Gets the value of the x1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX1() {
        return x1;
    }

    /**
     * Sets the value of the x1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX1(String value) {
        this.x1 = value;
    }

    /**
     * Gets the value of the x2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX2() {
        return x2;
    }

    /**
     * Sets the value of the x2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX2(String value) {
        this.x2 = value;
    }

    /**
     * Gets the value of the x3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX3() {
        return x3;
    }

    /**
     * Sets the value of the x3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX3(String value) {
        this.x3 = value;
    }

    /**
     * Gets the value of the x4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX4() {
        return x4;
    }

    /**
     * Sets the value of the x4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX4(String value) {
        this.x4 = value;
    }

    /**
     * Gets the value of the financialInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialInstitution() {
        return financialInstitution;
    }

    /**
     * Sets the value of the financialInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialInstitution(String value) {
        this.financialInstitution = value;
    }

    /**
     * Gets the value of the branchInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchInformation() {
        return branchInformation;
    }

    /**
     * Sets the value of the branchInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchInformation(String value) {
        this.branchInformation = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

}
