//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SenderReference" type="{urn:swift:saa:xsd:saa.2.0}SenderReference"/&gt;
 *         &lt;element name="ReceiverDeliveryStatus" type="{urn:swift:saa:xsd:saa.2.0}ReceiverDeliveryStatus"/&gt;
 *         &lt;element name="OriginalInstanceAddressee" type="{urn:swift:saa:xsd:saa.2.0}AddressFullName"/&gt;
 *         &lt;element name="ReportingApplication" type="{urn:swift:saa:xsd:saa.2.0}ReportingApplication"/&gt;
 *         &lt;element name="NetworkInfo" type="{urn:swift:saa:xsd:saa.2.0}NetworkInfo"/&gt;
 *         &lt;element name="SAAInfo" type="{urn:swift:saa:xsd:saa.2.0}SAAInfo" minOccurs="0"/&gt;
 *         &lt;element name="Interventions" type="{urn:swift:saa:xsd:saa.2.0}Interventions"/&gt;
 *         &lt;element name="IsRelatedInstanceOriginal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="RelatedInstanceAddressee" type="{urn:swift:saa:xsd:saa.2.0}AddressFullName" minOccurs="0"/&gt;
 *         &lt;element name="MessageCreator" type="{urn:swift:saa:xsd:saa.2.0}MessageCreator"/&gt;
 *         &lt;element name="IsMessageModified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="MessageFields" type="{urn:swift:saa:xsd:saa.2.0}MessageFields"/&gt;
 *         &lt;element name="Message" type="{urn:swift:saa:xsd:saa.2.0}Message" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryReport", propOrder = {
    "senderReference",
    "receiverDeliveryStatus",
    "originalInstanceAddressee",
    "reportingApplication",
    "networkInfo",
    "saaInfo",
    "interventions",
    "isRelatedInstanceOriginal",
    "relatedInstanceAddressee",
    "messageCreator",
    "isMessageModified",
    "messageFields",
    "message"
})
public class DeliveryReport {

    @XmlElement(name = "SenderReference", required = true)
    protected String senderReference;
    @XmlElement(name = "ReceiverDeliveryStatus", required = true)
    @XmlSchemaType(name = "string")
    protected ReceiverDeliveryStatus receiverDeliveryStatus;
    @XmlElement(name = "OriginalInstanceAddressee", required = true)
    protected AddressFullName originalInstanceAddressee;
    @XmlElement(name = "ReportingApplication", required = true)
    @XmlSchemaType(name = "string")
    protected ReportingApplication reportingApplication;
    @XmlElement(name = "NetworkInfo", required = true)
    protected NetworkInfo networkInfo;
    @XmlElement(name = "SAAInfo")
    protected SAAInfo saaInfo;
    @XmlElement(name = "Interventions", required = true)
    protected Interventions interventions;
    @XmlElement(name = "IsRelatedInstanceOriginal")
    protected boolean isRelatedInstanceOriginal;
    @XmlElement(name = "RelatedInstanceAddressee")
    protected AddressFullName relatedInstanceAddressee;
    @XmlElement(name = "MessageCreator", required = true)
    @XmlSchemaType(name = "string")
    protected MessageCreator messageCreator;
    @XmlElement(name = "IsMessageModified")
    protected boolean isMessageModified;
    @XmlElement(name = "MessageFields", required = true)
    @XmlSchemaType(name = "string")
    protected MessageFields messageFields;
    @XmlElement(name = "Message")
    protected Message message;

    /**
     * Gets the value of the senderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderReference() {
        return senderReference;
    }

    /**
     * Sets the value of the senderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderReference(String value) {
        this.senderReference = value;
    }

    /**
     * Gets the value of the receiverDeliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverDeliveryStatus }
     *     
     */
    public ReceiverDeliveryStatus getReceiverDeliveryStatus() {
        return receiverDeliveryStatus;
    }

    /**
     * Sets the value of the receiverDeliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverDeliveryStatus }
     *     
     */
    public void setReceiverDeliveryStatus(ReceiverDeliveryStatus value) {
        this.receiverDeliveryStatus = value;
    }

    /**
     * Gets the value of the originalInstanceAddressee property.
     * 
     * @return
     *     possible object is
     *     {@link AddressFullName }
     *     
     */
    public AddressFullName getOriginalInstanceAddressee() {
        return originalInstanceAddressee;
    }

    /**
     * Sets the value of the originalInstanceAddressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressFullName }
     *     
     */
    public void setOriginalInstanceAddressee(AddressFullName value) {
        this.originalInstanceAddressee = value;
    }

    /**
     * Gets the value of the reportingApplication property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingApplication }
     *     
     */
    public ReportingApplication getReportingApplication() {
        return reportingApplication;
    }

    /**
     * Sets the value of the reportingApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingApplication }
     *     
     */
    public void setReportingApplication(ReportingApplication value) {
        this.reportingApplication = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkInfo }
     *     
     */
    public NetworkInfo getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkInfo }
     *     
     */
    public void setNetworkInfo(NetworkInfo value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the saaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SAAInfo }
     *     
     */
    public SAAInfo getSAAInfo() {
        return saaInfo;
    }

    /**
     * Sets the value of the saaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAAInfo }
     *     
     */
    public void setSAAInfo(SAAInfo value) {
        this.saaInfo = value;
    }

    /**
     * Gets the value of the interventions property.
     * 
     * @return
     *     possible object is
     *     {@link Interventions }
     *     
     */
    public Interventions getInterventions() {
        return interventions;
    }

    /**
     * Sets the value of the interventions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interventions }
     *     
     */
    public void setInterventions(Interventions value) {
        this.interventions = value;
    }

    /**
     * Gets the value of the isRelatedInstanceOriginal property.
     * 
     */
    public boolean isIsRelatedInstanceOriginal() {
        return isRelatedInstanceOriginal;
    }

    /**
     * Sets the value of the isRelatedInstanceOriginal property.
     * 
     */
    public void setIsRelatedInstanceOriginal(boolean value) {
        this.isRelatedInstanceOriginal = value;
    }

    /**
     * Gets the value of the relatedInstanceAddressee property.
     * 
     * @return
     *     possible object is
     *     {@link AddressFullName }
     *     
     */
    public AddressFullName getRelatedInstanceAddressee() {
        return relatedInstanceAddressee;
    }

    /**
     * Sets the value of the relatedInstanceAddressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressFullName }
     *     
     */
    public void setRelatedInstanceAddressee(AddressFullName value) {
        this.relatedInstanceAddressee = value;
    }

    /**
     * Gets the value of the messageCreator property.
     * 
     * @return
     *     possible object is
     *     {@link MessageCreator }
     *     
     */
    public MessageCreator getMessageCreator() {
        return messageCreator;
    }

    /**
     * Sets the value of the messageCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageCreator }
     *     
     */
    public void setMessageCreator(MessageCreator value) {
        this.messageCreator = value;
    }

    /**
     * Gets the value of the isMessageModified property.
     * 
     */
    public boolean isIsMessageModified() {
        return isMessageModified;
    }

    /**
     * Sets the value of the isMessageModified property.
     * 
     */
    public void setIsMessageModified(boolean value) {
        this.isMessageModified = value;
    }

    /**
     * Gets the value of the messageFields property.
     * 
     * @return
     *     possible object is
     *     {@link MessageFields }
     *     
     */
    public MessageFields getMessageFields() {
        return messageFields;
    }

    /**
     * Sets the value of the messageFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageFields }
     *     
     */
    public void setMessageFields(MessageFields value) {
        this.messageFields = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link Message }
     *     
     */
    public Message getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message }
     *     
     */
    public void setMessage(Message value) {
        this.message = value;
    }

}
