//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReconciliationInfo" type="{urn:swift:saa:xsd:saa.2.0}SenderReference"/&gt;
 *         &lt;element name="ReceiverDeliveryStatus" type="{urn:swift:saa:xsd:saa.2.0}ReceiverDeliveryStatus"/&gt;
 *         &lt;element name="MessageIdentifier" type="{urn:swift:saa:xsd:saa.2.0}MessageIdentifier"/&gt;
 *         &lt;element name="Receiver" type="{urn:swift:saa:xsd:saa.2.0}AddressInfo" minOccurs="0"/&gt;
 *         &lt;element name="InterfaceInfo" type="{urn:swift:saa:xsd:saa.2.0}InterfaceInfo" minOccurs="0"/&gt;
 *         &lt;element name="NetworkInfo" type="{urn:swift:saa:xsd:saa.2.0}NetworkInfo" minOccurs="0"/&gt;
 *         &lt;element name="SecurityInfo" type="{urn:swift:saa:xsd:saa.2.0}SecurityInfo" minOccurs="0"/&gt;
 *         &lt;element name="SAAInfo" type="{urn:swift:saa:xsd:saa.2.0}SAAInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryNotification", propOrder = {
    "reconciliationInfo",
    "receiverDeliveryStatus",
    "messageIdentifier",
    "receiver",
    "interfaceInfo",
    "networkInfo",
    "securityInfo",
    "saaInfo"
})
public class DeliveryNotification {

    @XmlElement(name = "ReconciliationInfo", required = true)
    protected String reconciliationInfo;
    @XmlElement(name = "ReceiverDeliveryStatus", required = true)
    @XmlSchemaType(name = "string")
    protected ReceiverDeliveryStatus receiverDeliveryStatus;
    @XmlElement(name = "MessageIdentifier", required = true)
    protected String messageIdentifier;
    @XmlElement(name = "Receiver")
    protected AddressInfo receiver;
    @XmlElement(name = "InterfaceInfo")
    protected InterfaceInfo interfaceInfo;
    @XmlElement(name = "NetworkInfo")
    protected NetworkInfo networkInfo;
    @XmlElement(name = "SecurityInfo")
    protected SecurityInfo securityInfo;
    @XmlElement(name = "SAAInfo")
    protected SAAInfo saaInfo;

    /**
     * Gets the value of the reconciliationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconciliationInfo() {
        return reconciliationInfo;
    }

    /**
     * Sets the value of the reconciliationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconciliationInfo(String value) {
        this.reconciliationInfo = value;
    }

    /**
     * Gets the value of the receiverDeliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverDeliveryStatus }
     *     
     */
    public ReceiverDeliveryStatus getReceiverDeliveryStatus() {
        return receiverDeliveryStatus;
    }

    /**
     * Sets the value of the receiverDeliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverDeliveryStatus }
     *     
     */
    public void setReceiverDeliveryStatus(ReceiverDeliveryStatus value) {
        this.receiverDeliveryStatus = value;
    }

    /**
     * Gets the value of the messageIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageIdentifier() {
        return messageIdentifier;
    }

    /**
     * Sets the value of the messageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageIdentifier(String value) {
        this.messageIdentifier = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setReceiver(AddressInfo value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the interfaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceInfo }
     *     
     */
    public InterfaceInfo getInterfaceInfo() {
        return interfaceInfo;
    }

    /**
     * Sets the value of the interfaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceInfo }
     *     
     */
    public void setInterfaceInfo(InterfaceInfo value) {
        this.interfaceInfo = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkInfo }
     *     
     */
    public NetworkInfo getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkInfo }
     *     
     */
    public void setNetworkInfo(NetworkInfo value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the securityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityInfo }
     *     
     */
    public SecurityInfo getSecurityInfo() {
        return securityInfo;
    }

    /**
     * Sets the value of the securityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityInfo }
     *     
     */
    public void setSecurityInfo(SecurityInfo value) {
        this.securityInfo = value;
    }

    /**
     * Gets the value of the saaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SAAInfo }
     *     
     */
    public SAAInfo getSAAInfo() {
        return saaInfo;
    }

    /**
     * Sets the value of the saaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAAInfo }
     *     
     */
    public void setSAAInfo(SAAInfo value) {
        this.saaInfo = value;
    }

}
