//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FINNetworkInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FINNetworkInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserPriority" type="{urn:swift:saa:xsd:saa.2.0}UserPriority" minOccurs="0"/&gt;
 *         &lt;element name="CopyService" type="{urn:swift:saa:xsd:saa.2.0}CopyService" minOccurs="0"/&gt;
 *         &lt;element name="MessageSyntaxVersion" type="{urn:swift:saa:xsd:saa.2.0}MessageSyntaxVersion" minOccurs="0"/&gt;
 *         &lt;element name="IsRetrieved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReleaseInfo" type="{urn:swift:saa:xsd:saa.2.0}ReleaseInfo" minOccurs="0"/&gt;
 *         &lt;element name="ValidationIdentifier" type="{urn:swift:saa:xsd:saa.2.0}ValidationIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondentInputReference" type="{urn:swift:saa:xsd:saa.2.0}CorrespondentInputReference" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondentInputTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString" minOccurs="0"/&gt;
 *         &lt;element name="LocalOutputTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString" minOccurs="0"/&gt;
 *         &lt;element name="SystemOriginated" type="{urn:swift:saa:xsd:saa.2.0}FINTrailer" minOccurs="0"/&gt;
 *         &lt;element name="DelayedMessage" type="{urn:swift:saa:xsd:saa.2.0}FINTrailer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FINNetworkInfo", propOrder = {
    "userPriority",
    "copyService",
    "messageSyntaxVersion",
    "isRetrieved",
    "releaseInfo",
    "validationIdentifier",
    "correspondentInputReference",
    "correspondentInputTime",
    "localOutputTime",
    "systemOriginated",
    "delayedMessage"
})
public class FINNetworkInfo {

    @XmlElement(name = "UserPriority")
    protected String userPriority;
    @XmlElement(name = "CopyService")
    protected String copyService;
    @XmlElement(name = "MessageSyntaxVersion")
    protected String messageSyntaxVersion;
    @XmlElement(name = "IsRetrieved")
    protected Boolean isRetrieved;
    @XmlElement(name = "ReleaseInfo")
    protected String releaseInfo;
    @XmlElement(name = "ValidationIdentifier")
    protected String validationIdentifier;
    @XmlElement(name = "CorrespondentInputReference")
    protected String correspondentInputReference;
    @XmlElement(name = "CorrespondentInputTime")
    protected String correspondentInputTime;
    @XmlElement(name = "LocalOutputTime")
    protected String localOutputTime;
    @XmlElement(name = "SystemOriginated")
    protected String systemOriginated;
    @XmlElement(name = "DelayedMessage")
    protected String delayedMessage;

    /**
     * Gets the value of the userPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPriority() {
        return userPriority;
    }

    /**
     * Sets the value of the userPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPriority(String value) {
        this.userPriority = value;
    }

    /**
     * Gets the value of the copyService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyService() {
        return copyService;
    }

    /**
     * Sets the value of the copyService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyService(String value) {
        this.copyService = value;
    }

    /**
     * Gets the value of the messageSyntaxVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageSyntaxVersion() {
        return messageSyntaxVersion;
    }

    /**
     * Sets the value of the messageSyntaxVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageSyntaxVersion(String value) {
        this.messageSyntaxVersion = value;
    }

    /**
     * Gets the value of the isRetrieved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRetrieved() {
        return isRetrieved;
    }

    /**
     * Sets the value of the isRetrieved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRetrieved(Boolean value) {
        this.isRetrieved = value;
    }

    /**
     * Gets the value of the releaseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseInfo() {
        return releaseInfo;
    }

    /**
     * Sets the value of the releaseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseInfo(String value) {
        this.releaseInfo = value;
    }

    /**
     * Gets the value of the validationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationIdentifier() {
        return validationIdentifier;
    }

    /**
     * Sets the value of the validationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationIdentifier(String value) {
        this.validationIdentifier = value;
    }

    /**
     * Gets the value of the correspondentInputReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondentInputReference() {
        return correspondentInputReference;
    }

    /**
     * Sets the value of the correspondentInputReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondentInputReference(String value) {
        this.correspondentInputReference = value;
    }

    /**
     * Gets the value of the correspondentInputTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondentInputTime() {
        return correspondentInputTime;
    }

    /**
     * Sets the value of the correspondentInputTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondentInputTime(String value) {
        this.correspondentInputTime = value;
    }

    /**
     * Gets the value of the localOutputTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalOutputTime() {
        return localOutputTime;
    }

    /**
     * Sets the value of the localOutputTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalOutputTime(String value) {
        this.localOutputTime = value;
    }

    /**
     * Gets the value of the systemOriginated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemOriginated() {
        return systemOriginated;
    }

    /**
     * Sets the value of the systemOriginated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemOriginated(String value) {
        this.systemOriginated = value;
    }

    /**
     * Gets the value of the delayedMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayedMessage() {
        return delayedMessage;
    }

    /**
     * Sets the value of the delayedMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayedMessage(String value) {
        this.delayedMessage = value;
    }

}
