//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FINSecurityInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FINSecurityInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ChecksumResult" type="{urn:swift:saa:xsd:saa.2.0}ChecksumResult" minOccurs="0"/&gt;
 *         &lt;element name="ChecksumValue" type="{urn:swift:saa:xsd:saa.2.0}ChecksumValue" minOccurs="0"/&gt;
 *         &lt;element name="PACResult" type="{urn:swift:saa:xsd:saa.2.0}MACPACResult" minOccurs="0"/&gt;
 *         &lt;element name="PACValue" type="{urn:swift:saa:xsd:saa.2.0}MACPACValue" minOccurs="0"/&gt;
 *         &lt;element name="MACResult" type="{urn:swift:saa:xsd:saa.2.0}MACPACResult" minOccurs="0"/&gt;
 *         &lt;element name="MACValue" type="{urn:swift:saa:xsd:saa.2.0}MACPACValue" minOccurs="0"/&gt;
 *         &lt;element name="MACSignatureValue" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *         &lt;element name="PAC2SignatureValue" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FINSecurityInfo", propOrder = {
    "checksumResult",
    "checksumValue",
    "pacResult",
    "pacValue",
    "macResult",
    "macValue",
    "macSignatureValue",
    "pac2SignatureValue"
})
public class FINSecurityInfo {

    @XmlElement(name = "ChecksumResult")
    @XmlSchemaType(name = "string")
    protected ChecksumResult checksumResult;
    @XmlElement(name = "ChecksumValue")
    protected String checksumValue;
    @XmlElement(name = "PACResult")
    @XmlSchemaType(name = "string")
    protected MACPACResult pacResult;
    @XmlElement(name = "PACValue")
    protected String pacValue;
    @XmlElement(name = "MACResult")
    @XmlSchemaType(name = "string")
    protected MACPACResult macResult;
    @XmlElement(name = "MACValue")
    protected String macValue;
    @XmlElement(name = "MACSignatureValue")
    protected SwAny macSignatureValue;
    @XmlElement(name = "PAC2SignatureValue")
    protected SwAny pac2SignatureValue;

    /**
     * Gets the value of the checksumResult property.
     * 
     * @return
     *     possible object is
     *     {@link ChecksumResult }
     *     
     */
    public ChecksumResult getChecksumResult() {
        return checksumResult;
    }

    /**
     * Sets the value of the checksumResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChecksumResult }
     *     
     */
    public void setChecksumResult(ChecksumResult value) {
        this.checksumResult = value;
    }

    /**
     * Gets the value of the checksumValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecksumValue() {
        return checksumValue;
    }

    /**
     * Sets the value of the checksumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecksumValue(String value) {
        this.checksumValue = value;
    }

    /**
     * Gets the value of the pacResult property.
     * 
     * @return
     *     possible object is
     *     {@link MACPACResult }
     *     
     */
    public MACPACResult getPACResult() {
        return pacResult;
    }

    /**
     * Sets the value of the pacResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link MACPACResult }
     *     
     */
    public void setPACResult(MACPACResult value) {
        this.pacResult = value;
    }

    /**
     * Gets the value of the pacValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACValue() {
        return pacValue;
    }

    /**
     * Sets the value of the pacValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACValue(String value) {
        this.pacValue = value;
    }

    /**
     * Gets the value of the macResult property.
     * 
     * @return
     *     possible object is
     *     {@link MACPACResult }
     *     
     */
    public MACPACResult getMACResult() {
        return macResult;
    }

    /**
     * Sets the value of the macResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link MACPACResult }
     *     
     */
    public void setMACResult(MACPACResult value) {
        this.macResult = value;
    }

    /**
     * Gets the value of the macValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMACValue() {
        return macValue;
    }

    /**
     * Sets the value of the macValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMACValue(String value) {
        this.macValue = value;
    }

    /**
     * Gets the value of the macSignatureValue property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getMACSignatureValue() {
        return macSignatureValue;
    }

    /**
     * Sets the value of the macSignatureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setMACSignatureValue(SwAny value) {
        this.macSignatureValue = value;
    }

    /**
     * Gets the value of the pac2SignatureValue property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getPAC2SignatureValue() {
        return pac2SignatureValue;
    }

    /**
     * Sets the value of the pac2SignatureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setPAC2SignatureValue(SwAny value) {
        this.pac2SignatureValue = value;
    }

}
