//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Header complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Header"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Message" type="{urn:swift:saa:xsd:saa.2.0}Message"/&gt;
 *         &lt;element name="TransmissionReport" type="{urn:swift:saa:xsd:saa.2.0}TransmissionReport"/&gt;
 *         &lt;element name="DeliveryNotification" type="{urn:swift:saa:xsd:saa.2.0}DeliveryNotification"/&gt;
 *         &lt;element name="DeliveryReport" type="{urn:swift:saa:xsd:saa.2.0}DeliveryReport"/&gt;
 *         &lt;element name="HistoryReport" type="{urn:swift:saa:xsd:saa.2.0}HistoryReport"/&gt;
 *         &lt;element name="MessageStatus" type="{urn:swift:saa:xsd:saa.2.0}MessageStatus"/&gt;
 *         &lt;element name="SessionStatus" type="{urn:swift:saa:xsd:saa.2.0}SessionStatus"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header", propOrder = {
    "message",
    "transmissionReport",
    "deliveryNotification",
    "deliveryReport",
    "historyReport",
    "messageStatus",
    "sessionStatus"
})
public class Header {

    @Override
	public String toString() {
		return "\"Header\": {\"message\":\"" + message + "\", \"transmissionReport\":\"" + transmissionReport + "\", \"deliveryNotification\":\"" + deliveryNotification
				+ "\", \"deliveryReport\":\"" + deliveryReport + "\", \"historyReport\":\"" + historyReport + "\", \"messageStatus\":\"" + messageStatus + "\", \"sessionStatus\":\""
				+ sessionStatus + "\"}";
	}

	@XmlElement(name = "Message")
    protected Message message;
    @XmlElement(name = "TransmissionReport")
    protected TransmissionReport transmissionReport;
    @XmlElement(name = "DeliveryNotification")
    protected DeliveryNotification deliveryNotification;
    @XmlElement(name = "DeliveryReport")
    protected DeliveryReport deliveryReport;
    @XmlElement(name = "HistoryReport")
    protected HistoryReport historyReport;
    @XmlElement(name = "MessageStatus")
    protected MessageStatus messageStatus;
    @XmlElement(name = "SessionStatus")
    protected SessionStatus sessionStatus;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link Message }
     *     
     */
    public Message getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message }
     *     
     */
    public void setMessage(Message value) {
        this.message = value;
    }

    /**
     * Gets the value of the transmissionReport property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionReport }
     *     
     */
    public TransmissionReport getTransmissionReport() {
        return transmissionReport;
    }

    /**
     * Sets the value of the transmissionReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionReport }
     *     
     */
    public void setTransmissionReport(TransmissionReport value) {
        this.transmissionReport = value;
    }

    /**
     * Gets the value of the deliveryNotification property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryNotification }
     *     
     */
    public DeliveryNotification getDeliveryNotification() {
        return deliveryNotification;
    }

    /**
     * Sets the value of the deliveryNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryNotification }
     *     
     */
    public void setDeliveryNotification(DeliveryNotification value) {
        this.deliveryNotification = value;
    }

    /**
     * Gets the value of the deliveryReport property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryReport }
     *     
     */
    public DeliveryReport getDeliveryReport() {
        return deliveryReport;
    }

    /**
     * Sets the value of the deliveryReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryReport }
     *     
     */
    public void setDeliveryReport(DeliveryReport value) {
        this.deliveryReport = value;
    }

    /**
     * Gets the value of the historyReport property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryReport }
     *     
     */
    public HistoryReport getHistoryReport() {
        return historyReport;
    }

    /**
     * Sets the value of the historyReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryReport }
     *     
     */
    public void setHistoryReport(HistoryReport value) {
        this.historyReport = value;
    }

    /**
     * Gets the value of the messageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link MessageStatus }
     *     
     */
    public MessageStatus getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageStatus }
     *     
     */
    public void setMessageStatus(MessageStatus value) {
        this.messageStatus = value;
    }

    /**
     * Gets the value of the sessionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SessionStatus }
     *     
     */
    public SessionStatus getSessionStatus() {
        return sessionStatus;
    }

    /**
     * Sets the value of the sessionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionStatus }
     *     
     */
    public void setSessionStatus(SessionStatus value) {
        this.sessionStatus = value;
    }

}
