//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Intervention complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Intervention"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IntvCategory" type="{urn:swift:saa:xsd:saa.2.0}IntvCategory"/&gt;
 *         &lt;element name="CreationTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString"/&gt;
 *         &lt;element name="OperatorOrigin" type="{urn:swift:saa:xsd:saa.2.0}Operator"/&gt;
 *         &lt;element name="Contents" type="{urn:swift:saa:xsd:saa.2.0}SwAny"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Intervention", propOrder = {
    "intvCategory",
    "creationTime",
    "operatorOrigin",
    "contents"
})
public class Intervention {

    @XmlElement(name = "IntvCategory", required = true)
    @XmlSchemaType(name = "string")
    protected IntvCategory intvCategory;
    @XmlElement(name = "CreationTime", required = true)
    protected String creationTime;
    @XmlElement(name = "OperatorOrigin", required = true)
    protected String operatorOrigin;
    @XmlElement(name = "Contents", required = true)
    protected SwAny contents;

    /**
     * Gets the value of the intvCategory property.
     * 
     * @return
     *     possible object is
     *     {@link IntvCategory }
     *     
     */
    public IntvCategory getIntvCategory() {
        return intvCategory;
    }

    /**
     * Sets the value of the intvCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntvCategory }
     *     
     */
    public void setIntvCategory(IntvCategory value) {
        this.intvCategory = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the operatorOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorOrigin() {
        return operatorOrigin;
    }

    /**
     * Sets the value of the operatorOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorOrigin(String value) {
        this.operatorOrigin = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setContents(SwAny value) {
        this.contents = value;
    }

}
