//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntvCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IntvCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TransmissionReport"/&gt;
 *     &lt;enumeration value="DeliveryReport"/&gt;
 *     &lt;enumeration value="TransmissionResponse"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IntvCategory")
@XmlEnum
public enum IntvCategory {

    @XmlEnumValue("TransmissionReport")
    TRANSMISSION_REPORT("TransmissionReport"),
    @XmlEnumValue("DeliveryReport")
    DELIVERY_REPORT("DeliveryReport"),
    @XmlEnumValue("TransmissionResponse")
    TRANSMISSION_RESPONSE("TransmissionResponse");
    private final String value;

    IntvCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntvCategory fromValue(String v) {
        for (IntvCategory c: IntvCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
