//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageNature.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageNature"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Financial"/&gt;
 *     &lt;enumeration value="Text"/&gt;
 *     &lt;enumeration value="Network"/&gt;
 *     &lt;enumeration value="Security"/&gt;
 *     &lt;enumeration value="Service"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageNature")
@XmlEnum
public enum MessageNature {

    @XmlEnumValue("Financial")
    FINANCIAL("Financial"),
    @XmlEnumValue("Text")
    TEXT("Text"),
    @XmlEnumValue("Network")
    NETWORK("Network"),
    @XmlEnumValue("Security")
    SECURITY("Security"),
    @XmlEnumValue("Service")
    SERVICE("Service");
    private final String value;

    MessageNature(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageNature fromValue(String v) {
        for (MessageNature c: MessageNature.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
