//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SenderReference" type="{urn:swift:saa:xsd:saa.2.0}SenderReference"/&gt;
 *         &lt;element name="MessageIdentifier" type="{urn:swift:saa:xsd:saa.2.0}MessageIdentifier"/&gt;
 *         &lt;element name="Format" type="{urn:swift:saa:xsd:saa.2.0}Format"/&gt;
 *         &lt;element name="SubFormat" type="{urn:swift:saa:xsd:saa.2.0}SubFormat" minOccurs="0"/&gt;
 *         &lt;element name="Sender" type="{urn:swift:saa:xsd:saa.2.0}AddressInfo"/&gt;
 *         &lt;element name="Receiver" type="{urn:swift:saa:xsd:saa.2.0}AddressInfo"/&gt;
 *         &lt;element name="InterfaceInfo" type="{urn:swift:saa:xsd:saa.2.0}InterfaceInfo" minOccurs="0"/&gt;
 *         &lt;element name="NetworkInfo" type="{urn:swift:saa:xsd:saa.2.0}NetworkInfo" minOccurs="0"/&gt;
 *         &lt;element name="SecurityInfo" type="{urn:swift:saa:xsd:saa.2.0}SecurityInfo" minOccurs="0"/&gt;
 *         &lt;element name="SAAInfo" type="{urn:swift:saa:xsd:saa.2.0}SAAInfo" minOccurs="0"/&gt;
 *         &lt;element name="FileLogicalName" type="{urn:swift:saa:xsd:saa.2.0}FileLogicalName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "senderReference",
    "messageIdentifier",
    "format",
    "subFormat",
    "sender",
    "receiver",
    "interfaceInfo",
    "networkInfo",
    "securityInfo",
    "saaInfo",
    "fileLogicalName"
})
public class Message {

    @XmlElement(name = "SenderReference", required = true)
    protected String senderReference;
    @XmlElement(name = "MessageIdentifier", required = true)
    protected String messageIdentifier;
    @XmlElement(name = "Format", required = true)
    protected String format;
    @XmlElement(name = "SubFormat")
    @XmlSchemaType(name = "string")
    protected SubFormat subFormat;
    @XmlElement(name = "Sender", required = true)
    protected AddressInfo sender;

	@XmlElement(name = "Receiver", required = true)
    protected AddressInfo receiver;
    @XmlElement(name = "InterfaceInfo")
    protected InterfaceInfo interfaceInfo;
    @XmlElement(name = "NetworkInfo")
    protected NetworkInfo networkInfo;
    @XmlElement(name = "SecurityInfo")
    protected SecurityInfo securityInfo;
    @XmlElement(name = "SAAInfo")
    protected SAAInfo saaInfo;
    @XmlElement(name = "FileLogicalName")
    protected String fileLogicalName;

    /**
     * Gets the value of the senderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderReference() {
        return senderReference;
    }

    /**
     * Sets the value of the senderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderReference(String value) {
        this.senderReference = value;
    }

    /**
     * Gets the value of the messageIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageIdentifier() {
        return messageIdentifier;
    }

    /**
     * Sets the value of the messageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageIdentifier(String value) {
        this.messageIdentifier = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the subFormat property.
     * 
     * @return
     *     possible object is
     *     {@link SubFormat }
     *     
     */
    public SubFormat getSubFormat() {
        return subFormat;
    }

    /**
     * Sets the value of the subFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubFormat }
     *     
     */
    public void setSubFormat(SubFormat value) {
        this.subFormat = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setSender(AddressInfo value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setReceiver(AddressInfo value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the interfaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceInfo }
     *     
     */
    public InterfaceInfo getInterfaceInfo() {
        return interfaceInfo;
    }

    /**
     * Sets the value of the interfaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceInfo }
     *     
     */
    public void setInterfaceInfo(InterfaceInfo value) {
        this.interfaceInfo = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkInfo }
     *     
     */
    public NetworkInfo getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkInfo }
     *     
     */
    public void setNetworkInfo(NetworkInfo value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the securityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityInfo }
     *     
     */
    public SecurityInfo getSecurityInfo() {
        return securityInfo;
    }

    /**
     * Sets the value of the securityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityInfo }
     *     
     */
    public void setSecurityInfo(SecurityInfo value) {
        this.securityInfo = value;
    }

    /**
     * Gets the value of the saaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SAAInfo }
     *     
     */
    public SAAInfo getSAAInfo() {
        return saaInfo;
    }

    /**
     * Sets the value of the saaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAAInfo }
     *     
     */
    public void setSAAInfo(SAAInfo value) {
        this.saaInfo = value;
    }

    /**
     * Gets the value of the fileLogicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLogicalName() {
        return fileLogicalName;
    }

    /**
     * Sets the value of the fileLogicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLogicalName(String value) {
        this.fileLogicalName = value;
    }

}
