//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:swift:saa:xsd:saa.2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eastnets.mx.mapping;
