//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PDEPDM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDEPDM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="PDE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PDM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDEPDM", propOrder = {
    "pdeOrPDM"
})
public class PDEPDM {

    @XmlElementRefs({
        @XmlElementRef(name = "PDM", namespace = "urn:swift:saa:xsd:saa.2.0", type = JAXBElement.class),
        @XmlElementRef(name = "PDE", namespace = "urn:swift:saa:xsd:saa.2.0", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> pdeOrPDM;

    /**
     * Gets the value of the pdeOrPDM property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pdeOrPDM property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPDEOrPDM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getPDEOrPDM() {
        if (pdeOrPDM == null) {
            pdeOrPDM = new ArrayList<JAXBElement<String>>();
        }
        return this.pdeOrPDM;
    }

}
