//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceiverDeliveryStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReceiverDeliveryStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RcvDelivered"/&gt;
 *     &lt;enumeration value="RcvAborted"/&gt;
 *     &lt;enumeration value="RcvDelayedNak"/&gt;
 *     &lt;enumeration value="RcvFCPReleased"/&gt;
 *     &lt;enumeration value="RcvOverdue"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReceiverDeliveryStatus")
@XmlEnum
public enum ReceiverDeliveryStatus {

    @XmlEnumValue("RcvDelivered")
    RCV_DELIVERED("RcvDelivered"),
    @XmlEnumValue("RcvAborted")
    RCV_ABORTED("RcvAborted"),
    @XmlEnumValue("RcvDelayedNak")
    RCV_DELAYED_NAK("RcvDelayedNak"),
    @XmlEnumValue("RcvFCPReleased")
    RCV_FCP_RELEASED("RcvFCPReleased"),
    @XmlEnumValue("RcvOverdue")
    RCV_OVERDUE("RcvOverdue");
    private final String value;

    ReceiverDeliveryStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReceiverDeliveryStatus fromValue(String v) {
        for (ReceiverDeliveryStatus c: ReceiverDeliveryStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
