//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RMAResult.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RMAResult"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Success"/&gt;
 *     &lt;enumeration value="Bypassed"/&gt;
 *     &lt;enumeration value="NoRecord"/&gt;
 *     &lt;enumeration value="NotEnabled"/&gt;
 *     &lt;enumeration value="InvalidPeriod"/&gt;
 *     &lt;enumeration value="Unauthorised"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RMAResult")
@XmlEnum
public enum RMAResult {

    @XmlEnumValue("Success")
    SUCCESS("Success"),
    @XmlEnumValue("Bypassed")
    BYPASSED("Bypassed"),
    @XmlEnumValue("NoRecord")
    NO_RECORD("NoRecord"),
    @XmlEnumValue("NotEnabled")
    NOT_ENABLED("NotEnabled"),
    @XmlEnumValue("InvalidPeriod")
    INVALID_PERIOD("InvalidPeriod"),
    @XmlEnumValue("Unauthorised")
    UNAUTHORISED("Unauthorised");
    private final String value;

    RMAResult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RMAResult fromValue(String v) {
        for (RMAResult c: RMAResult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
