//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutingFunction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoutingFunction"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Route"/&gt;
 *     &lt;enumeration value="DisposeToRoutingStep"/&gt;
 *     &lt;enumeration value="DisposeToRoutingPoint"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RoutingFunction")
@XmlEnum
public enum RoutingFunction {

    @XmlEnumValue("Route")
    ROUTE("Route"),
    @XmlEnumValue("DisposeToRoutingStep")
    DISPOSE_TO_ROUTING_STEP("DisposeToRoutingStep"),
    @XmlEnumValue("DisposeToRoutingPoint")
    DISPOSE_TO_ROUTING_POINT("DisposeToRoutingPoint");
    private final String value;

    RoutingFunction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoutingFunction fromValue(String v) {
        for (RoutingFunction c: RoutingFunction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
