//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutingInstruction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutingInstruction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RoutingFunction" type="{urn:swift:saa:xsd:saa.2.0}RoutingFunction"/&gt;
 *         &lt;element name="RoutingPoint" type="{urn:swift:saa:xsd:saa.2.0}RoutingPoint" minOccurs="0"/&gt;
 *         &lt;element name="RoutingStep" type="{urn:swift:saa:xsd:saa.2.0}RoutingStep" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutingInstruction", propOrder = {
    "routingFunction",
    "routingPoint",
    "routingStep"
})
public class RoutingInstruction {

    @XmlElement(name = "RoutingFunction", required = true)
    @XmlSchemaType(name = "string")
    protected RoutingFunction routingFunction;
    @XmlElement(name = "RoutingPoint")
    protected String routingPoint;
    @XmlElement(name = "RoutingStep")
    @XmlSchemaType(name = "string")
    protected RoutingStep routingStep;

    /**
     * Gets the value of the routingFunction property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingFunction }
     *     
     */
    public RoutingFunction getRoutingFunction() {
        return routingFunction;
    }

    /**
     * Sets the value of the routingFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingFunction }
     *     
     */
    public void setRoutingFunction(RoutingFunction value) {
        this.routingFunction = value;
    }

    /**
     * Gets the value of the routingPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingPoint() {
        return routingPoint;
    }

    /**
     * Sets the value of the routingPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingPoint(String value) {
        this.routingPoint = value;
    }

    /**
     * Gets the value of the routingStep property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingStep }
     *     
     */
    public RoutingStep getRoutingStep() {
        return routingStep;
    }

    /**
     * Sets the value of the routingStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingStep }
     *     
     */
    public void setRoutingStep(RoutingStep value) {
        this.routingStep = value;
    }

}
