//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SessionStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SessionStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessagePartner" type="{urn:swift:saa:xsd:saa.2.0}MessagePartner"/&gt;
 *         &lt;element name="CreationTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString"/&gt;
 *         &lt;element name="SessionNr" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="InputFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsSuccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ErrorText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SessionDirection" type="{urn:swift:saa:xsd:saa.2.0}SessionDirection" minOccurs="0"/&gt;
 *         &lt;element name="Accepted" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Rejected" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="AcceptedFromMessagePartner" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="RejectedFromMessagePartner" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="AcceptedToMessagePartner" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="RejectedToMessagePartner" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SessionStatus", propOrder = {
    "messagePartner",
    "creationTime",
    "sessionNr",
    "inputFile",
    "isSuccess",
    "errorCode",
    "errorText",
    "sessionDirection",
    "accepted",
    "rejected",
    "acceptedFromMessagePartner",
    "rejectedFromMessagePartner",
    "acceptedToMessagePartner",
    "rejectedToMessagePartner"
})
public class SessionStatus {

    @XmlElement(name = "MessagePartner", required = true)
    protected String messagePartner;
    @XmlElement(name = "CreationTime", required = true)
    protected String creationTime;
    @XmlElement(name = "SessionNr")
    protected int sessionNr;
    @XmlElement(name = "InputFile")
    protected String inputFile;
    @XmlElement(name = "IsSuccess")
    protected boolean isSuccess;
    @XmlElement(name = "ErrorCode")
    protected String errorCode;
    @XmlElement(name = "ErrorText")
    protected String errorText;
    @XmlElement(name = "SessionDirection")
    @XmlSchemaType(name = "string")
    protected SessionDirection sessionDirection;
    @XmlElement(name = "Accepted")
    protected Integer accepted;
    @XmlElement(name = "Rejected")
    protected Integer rejected;
    @XmlElement(name = "AcceptedFromMessagePartner")
    protected Integer acceptedFromMessagePartner;
    @XmlElement(name = "RejectedFromMessagePartner")
    protected Integer rejectedFromMessagePartner;
    @XmlElement(name = "AcceptedToMessagePartner")
    protected Integer acceptedToMessagePartner;
    @XmlElement(name = "RejectedToMessagePartner")
    protected Integer rejectedToMessagePartner;

    /**
     * Gets the value of the messagePartner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessagePartner() {
        return messagePartner;
    }

    /**
     * Sets the value of the messagePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessagePartner(String value) {
        this.messagePartner = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the sessionNr property.
     * 
     */
    public int getSessionNr() {
        return sessionNr;
    }

    /**
     * Sets the value of the sessionNr property.
     * 
     */
    public void setSessionNr(int value) {
        this.sessionNr = value;
    }

    /**
     * Gets the value of the inputFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFile() {
        return inputFile;
    }

    /**
     * Sets the value of the inputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFile(String value) {
        this.inputFile = value;
    }

    /**
     * Gets the value of the isSuccess property.
     * 
     */
    public boolean isIsSuccess() {
        return isSuccess;
    }

    /**
     * Sets the value of the isSuccess property.
     * 
     */
    public void setIsSuccess(boolean value) {
        this.isSuccess = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Sets the value of the errorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorText(String value) {
        this.errorText = value;
    }

    /**
     * Gets the value of the sessionDirection property.
     * 
     * @return
     *     possible object is
     *     {@link SessionDirection }
     *     
     */
    public SessionDirection getSessionDirection() {
        return sessionDirection;
    }

    /**
     * Sets the value of the sessionDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionDirection }
     *     
     */
    public void setSessionDirection(SessionDirection value) {
        this.sessionDirection = value;
    }

    /**
     * Gets the value of the accepted property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccepted() {
        return accepted;
    }

    /**
     * Sets the value of the accepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccepted(Integer value) {
        this.accepted = value;
    }

    /**
     * Gets the value of the rejected property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRejected() {
        return rejected;
    }

    /**
     * Sets the value of the rejected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRejected(Integer value) {
        this.rejected = value;
    }

    /**
     * Gets the value of the acceptedFromMessagePartner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcceptedFromMessagePartner() {
        return acceptedFromMessagePartner;
    }

    /**
     * Sets the value of the acceptedFromMessagePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcceptedFromMessagePartner(Integer value) {
        this.acceptedFromMessagePartner = value;
    }

    /**
     * Gets the value of the rejectedFromMessagePartner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRejectedFromMessagePartner() {
        return rejectedFromMessagePartner;
    }

    /**
     * Sets the value of the rejectedFromMessagePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRejectedFromMessagePartner(Integer value) {
        this.rejectedFromMessagePartner = value;
    }

    /**
     * Gets the value of the acceptedToMessagePartner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcceptedToMessagePartner() {
        return acceptedToMessagePartner;
    }

    /**
     * Sets the value of the acceptedToMessagePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcceptedToMessagePartner(Integer value) {
        this.acceptedToMessagePartner = value;
    }

    /**
     * Gets the value of the rejectedToMessagePartner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRejectedToMessagePartner() {
        return rejectedToMessagePartner;
    }

    /**
     * Sets the value of the rejectedToMessagePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRejectedToMessagePartner(Integer value) {
        this.rejectedToMessagePartner = value;
    }

}
