//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:31:47 PM EET 
//


package com.eastnets.mx.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SWIFTNetNetworkInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SWIFTNetNetworkInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestType" type="{urn:swift:saa:xsd:saa.2.0}RequestType" minOccurs="0"/&gt;
 *         &lt;element name="SWIFTRef" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetReference" minOccurs="0"/&gt;
 *         &lt;element name="SNLRef" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetReference" minOccurs="0"/&gt;
 *         &lt;element name="Reference" type="{urn:swift:saa:xsd:saa.2.0}CBTReference" minOccurs="0"/&gt;
 *         &lt;element name="SNLEndPoint" type="{urn:swift:saa:xsd:saa.2.0}SNLEndPoint" minOccurs="0"/&gt;
 *         &lt;element name="SnFQueueName" type="{urn:swift:saa:xsd:saa.2.0}SnFQueueName" minOccurs="0"/&gt;
 *         &lt;element name="SnFInputTime" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetTime" minOccurs="0"/&gt;
 *         &lt;element name="SnFDeliveryTime" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetTime" minOccurs="0"/&gt;
 *         &lt;element name="CreationTime" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetTime" minOccurs="0"/&gt;
 *         &lt;element name="ValidationDescriptor" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *         &lt;element name="ResponseResponderDN" type="{urn:swift:saa:xsd:saa.2.0}DN" minOccurs="0"/&gt;
 *         &lt;element name="ResponseSWIFTRef" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetReference" minOccurs="0"/&gt;
 *         &lt;element name="ResponseSNLRef" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetReference" minOccurs="0"/&gt;
 *         &lt;element name="ResponseReference" type="{urn:swift:saa:xsd:saa.2.0}CBTReference" minOccurs="0"/&gt;
 *         &lt;element name="IsPossibleDuplicateResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ResponseValidationDescriptor" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *         &lt;element name="PayloadAttributes" type="{urn:swift:saa:xsd:saa.2.0}PayloadAttributeList" minOccurs="0"/&gt;
 *         &lt;element name="ResponsePayloadAttributes" type="{urn:swift:saa:xsd:saa.2.0}PayloadAttributeList" minOccurs="0"/&gt;
 *         &lt;element name="IsCopyRequested" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsAuthNotificationRequested" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CopyInfo" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *         &lt;element name="TransferRef" type="{urn:swift:saa:xsd:saa.2.0}TransferRef" minOccurs="0"/&gt;
 *         &lt;element name="StoredTransferRef" type="{urn:swift:saa:xsd:saa.2.0}TransferRef" minOccurs="0"/&gt;
 *         &lt;element name="OrigSnfRef" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetReference" minOccurs="0"/&gt;
 *         &lt;element name="TransferDescription" type="{urn:swift:saa:xsd:saa.2.0}FileInfoDescription" minOccurs="0"/&gt;
 *         &lt;element name="TransferInfo" type="{urn:swift:saa:xsd:saa.2.0}FileInfoDescription" minOccurs="0"/&gt;
 *         &lt;element name="FileDescription" type="{urn:swift:saa:xsd:saa.2.0}FileInfoDescription" minOccurs="0"/&gt;
 *         &lt;element name="FileInfo" type="{urn:swift:saa:xsd:saa.2.0}FileInfoDescription" minOccurs="0"/&gt;
 *         &lt;element name="HeaderInfo" type="{urn:swift:saa:xsd:saa.2.0}SwAny" minOccurs="0"/&gt;
 *         &lt;element name="NotificationResponderDN" type="{urn:swift:saa:xsd:saa.2.0}DN" minOccurs="0"/&gt;
 *         &lt;element name="NotificationRequestType" type="{urn:swift:saa:xsd:saa.2.0}RequestType" minOccurs="0"/&gt;
 *         &lt;element name="FileStartTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString" minOccurs="0"/&gt;
 *         &lt;element name="FileEndTime" type="{urn:swift:saa:xsd:saa.2.0}TimeString" minOccurs="0"/&gt;
 *         &lt;element name="OverdueWarningTime" type="{urn:swift:saa:xsd:saa.2.0}SWIFTNetTime" minOccurs="0"/&gt;
 *         &lt;element name="OverdueWarningDelay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SWIFTNetNetworkInfo", propOrder = {
    "requestType",
    "swiftRef",
    "snlRef",
    "reference",
    "snlEndPoint",
    "snFQueueName",
    "snFInputTime",
    "snFDeliveryTime",
    "creationTime",
    "validationDescriptor",
    "responseResponderDN",
    "responseSWIFTRef",
    "responseSNLRef",
    "responseReference",
    "isPossibleDuplicateResponse",
    "responseValidationDescriptor",
    "payloadAttributes",
    "responsePayloadAttributes",
    "isCopyRequested",
    "isAuthNotificationRequested",
    "copyInfo",
    "transferRef",
    "storedTransferRef",
    "origSnfRef",
    "transferDescription",
    "transferInfo",
    "fileDescription",
    "fileInfo",
    "headerInfo",
    "notificationResponderDN",
    "notificationRequestType",
    "fileStartTime",
    "fileEndTime",
    "overdueWarningTime",
    "overdueWarningDelay"
})
public class SWIFTNetNetworkInfo {

    @XmlElement(name = "RequestType")
    protected String requestType;
    @XmlElement(name = "SWIFTRef")
    protected String swiftRef;
    @XmlElement(name = "SNLRef")
    protected String snlRef;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "SNLEndPoint")
    protected String snlEndPoint;
    @XmlElement(name = "SnFQueueName")
    protected String snFQueueName;
    @XmlElement(name = "SnFInputTime")
    protected String snFInputTime;
    @XmlElement(name = "SnFDeliveryTime")
    protected String snFDeliveryTime;
    @XmlElement(name = "CreationTime")
    protected String creationTime;
    @XmlElement(name = "ValidationDescriptor")
    protected SwAny validationDescriptor;
    @XmlElement(name = "ResponseResponderDN")
    protected String responseResponderDN;
    @XmlElement(name = "ResponseSWIFTRef")
    protected String responseSWIFTRef;
    @XmlElement(name = "ResponseSNLRef")
    protected String responseSNLRef;
    @XmlElement(name = "ResponseReference")
    protected String responseReference;
    @XmlElement(name = "IsPossibleDuplicateResponse")
    protected Boolean isPossibleDuplicateResponse;
    @XmlElement(name = "ResponseValidationDescriptor")
    protected SwAny responseValidationDescriptor;
    @XmlElement(name = "PayloadAttributes")
    protected PayloadAttributeList payloadAttributes;
    @XmlElement(name = "ResponsePayloadAttributes")
    protected PayloadAttributeList responsePayloadAttributes;
    @XmlElement(name = "IsCopyRequested")
    protected Boolean isCopyRequested;
    @XmlElement(name = "IsAuthNotificationRequested")
    protected Boolean isAuthNotificationRequested;
    @XmlElement(name = "CopyInfo")
    protected SwAny copyInfo;
    @XmlElement(name = "TransferRef")
    protected String transferRef;
    @XmlElement(name = "StoredTransferRef")
    protected String storedTransferRef;
    @XmlElement(name = "OrigSnfRef")
    protected String origSnfRef;
    @XmlElement(name = "TransferDescription")
    protected String transferDescription;
    @XmlElement(name = "TransferInfo")
    protected String transferInfo;
    @XmlElement(name = "FileDescription")
    protected String fileDescription;
    @XmlElement(name = "FileInfo")
    protected String fileInfo;
    @XmlElement(name = "HeaderInfo")
    protected SwAny headerInfo;
    @XmlElement(name = "NotificationResponderDN")
    protected String notificationResponderDN;
    @XmlElement(name = "NotificationRequestType")
    protected String notificationRequestType;
    @XmlElement(name = "FileStartTime")
    protected String fileStartTime;
    @XmlElement(name = "FileEndTime")
    protected String fileEndTime;
    @XmlElement(name = "OverdueWarningTime")
    protected String overdueWarningTime;
    @XmlElement(name = "OverdueWarningDelay")
    protected Integer overdueWarningDelay;

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the swiftRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFTRef() {
        return swiftRef;
    }

    /**
     * Sets the value of the swiftRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFTRef(String value) {
        this.swiftRef = value;
    }

    /**
     * Gets the value of the snlRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNLRef() {
        return snlRef;
    }

    /**
     * Sets the value of the snlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNLRef(String value) {
        this.snlRef = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the snlEndPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNLEndPoint() {
        return snlEndPoint;
    }

    /**
     * Sets the value of the snlEndPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNLEndPoint(String value) {
        this.snlEndPoint = value;
    }

    /**
     * Gets the value of the snFQueueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnFQueueName() {
        return snFQueueName;
    }

    /**
     * Sets the value of the snFQueueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnFQueueName(String value) {
        this.snFQueueName = value;
    }

    /**
     * Gets the value of the snFInputTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnFInputTime() {
        return snFInputTime;
    }

    /**
     * Sets the value of the snFInputTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnFInputTime(String value) {
        this.snFInputTime = value;
    }

    /**
     * Gets the value of the snFDeliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnFDeliveryTime() {
        return snFDeliveryTime;
    }

    /**
     * Sets the value of the snFDeliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnFDeliveryTime(String value) {
        this.snFDeliveryTime = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the validationDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getValidationDescriptor() {
        return validationDescriptor;
    }

    /**
     * Sets the value of the validationDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setValidationDescriptor(SwAny value) {
        this.validationDescriptor = value;
    }

    /**
     * Gets the value of the responseResponderDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseResponderDN() {
        return responseResponderDN;
    }

    /**
     * Sets the value of the responseResponderDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseResponderDN(String value) {
        this.responseResponderDN = value;
    }

    /**
     * Gets the value of the responseSWIFTRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseSWIFTRef() {
        return responseSWIFTRef;
    }

    /**
     * Sets the value of the responseSWIFTRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseSWIFTRef(String value) {
        this.responseSWIFTRef = value;
    }

    /**
     * Gets the value of the responseSNLRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseSNLRef() {
        return responseSNLRef;
    }

    /**
     * Sets the value of the responseSNLRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseSNLRef(String value) {
        this.responseSNLRef = value;
    }

    /**
     * Gets the value of the responseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseReference() {
        return responseReference;
    }

    /**
     * Sets the value of the responseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseReference(String value) {
        this.responseReference = value;
    }

    /**
     * Gets the value of the isPossibleDuplicateResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPossibleDuplicateResponse() {
        return isPossibleDuplicateResponse;
    }

    /**
     * Sets the value of the isPossibleDuplicateResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPossibleDuplicateResponse(Boolean value) {
        this.isPossibleDuplicateResponse = value;
    }

    /**
     * Gets the value of the responseValidationDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getResponseValidationDescriptor() {
        return responseValidationDescriptor;
    }

    /**
     * Sets the value of the responseValidationDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setResponseValidationDescriptor(SwAny value) {
        this.responseValidationDescriptor = value;
    }

    /**
     * Gets the value of the payloadAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadAttributeList }
     *     
     */
    public PayloadAttributeList getPayloadAttributes() {
        return payloadAttributes;
    }

    /**
     * Sets the value of the payloadAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadAttributeList }
     *     
     */
    public void setPayloadAttributes(PayloadAttributeList value) {
        this.payloadAttributes = value;
    }

    /**
     * Gets the value of the responsePayloadAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadAttributeList }
     *     
     */
    public PayloadAttributeList getResponsePayloadAttributes() {
        return responsePayloadAttributes;
    }

    /**
     * Sets the value of the responsePayloadAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadAttributeList }
     *     
     */
    public void setResponsePayloadAttributes(PayloadAttributeList value) {
        this.responsePayloadAttributes = value;
    }

    /**
     * Gets the value of the isCopyRequested property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCopyRequested() {
        return isCopyRequested;
    }

    /**
     * Sets the value of the isCopyRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCopyRequested(Boolean value) {
        this.isCopyRequested = value;
    }

    /**
     * Gets the value of the isAuthNotificationRequested property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAuthNotificationRequested() {
        return isAuthNotificationRequested;
    }

    /**
     * Sets the value of the isAuthNotificationRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAuthNotificationRequested(Boolean value) {
        this.isAuthNotificationRequested = value;
    }

    /**
     * Gets the value of the copyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getCopyInfo() {
        return copyInfo;
    }

    /**
     * Sets the value of the copyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setCopyInfo(SwAny value) {
        this.copyInfo = value;
    }

    /**
     * Gets the value of the transferRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferRef() {
        return transferRef;
    }

    /**
     * Sets the value of the transferRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferRef(String value) {
        this.transferRef = value;
    }

    /**
     * Gets the value of the storedTransferRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoredTransferRef() {
        return storedTransferRef;
    }

    /**
     * Sets the value of the storedTransferRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoredTransferRef(String value) {
        this.storedTransferRef = value;
    }

    /**
     * Gets the value of the origSnfRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigSnfRef() {
        return origSnfRef;
    }

    /**
     * Sets the value of the origSnfRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigSnfRef(String value) {
        this.origSnfRef = value;
    }

    /**
     * Gets the value of the transferDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferDescription() {
        return transferDescription;
    }

    /**
     * Sets the value of the transferDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferDescription(String value) {
        this.transferDescription = value;
    }

    /**
     * Gets the value of the transferInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferInfo() {
        return transferInfo;
    }

    /**
     * Sets the value of the transferInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferInfo(String value) {
        this.transferInfo = value;
    }

    /**
     * Gets the value of the fileDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * Sets the value of the fileDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDescription(String value) {
        this.fileDescription = value;
    }

    /**
     * Gets the value of the fileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileInfo() {
        return fileInfo;
    }

    /**
     * Sets the value of the fileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileInfo(String value) {
        this.fileInfo = value;
    }

    /**
     * Gets the value of the headerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SwAny }
     *     
     */
    public SwAny getHeaderInfo() {
        return headerInfo;
    }

    /**
     * Sets the value of the headerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwAny }
     *     
     */
    public void setHeaderInfo(SwAny value) {
        this.headerInfo = value;
    }

    /**
     * Gets the value of the notificationResponderDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationResponderDN() {
        return notificationResponderDN;
    }

    /**
     * Sets the value of the notificationResponderDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationResponderDN(String value) {
        this.notificationResponderDN = value;
    }

    /**
     * Gets the value of the notificationRequestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationRequestType() {
        return notificationRequestType;
    }

    /**
     * Sets the value of the notificationRequestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationRequestType(String value) {
        this.notificationRequestType = value;
    }

    /**
     * Gets the value of the fileStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileStartTime() {
        return fileStartTime;
    }

    /**
     * Sets the value of the fileStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileStartTime(String value) {
        this.fileStartTime = value;
    }

    /**
     * Gets the value of the fileEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileEndTime() {
        return fileEndTime;
    }

    /**
     * Sets the value of the fileEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileEndTime(String value) {
        this.fileEndTime = value;
    }

    /**
     * Gets the value of the overdueWarningTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverdueWarningTime() {
        return overdueWarningTime;
    }

    /**
     * Sets the value of the overdueWarningTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverdueWarningTime(String value) {
        this.overdueWarningTime = value;
    }

    /**
     * Gets the value of the overdueWarningDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverdueWarningDelay() {
        return overdueWarningDelay;
    }

    /**
     * Sets the value of the overdueWarningDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverdueWarningDelay(Integer value) {
        this.overdueWarningDelay = value;
    }

}
