/*
 * Generated by JasperReports - 6/18/13 2:16 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class Fin32messages324532subtotals32by32Receiver4432Message32Type32And32Currency_1371554216306_569972 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_P_SENDER = null;
    private JRFillParameter parameter_P_DBPREFIX = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_P_DATETIMEPATTERN = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_CP_MESG_TRN_REF = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_CP_AMOUNT_EXP = null;
    private JRFillParameter parameter_P_ORACLEROWNUMCONDITION = null;
    private JRFillParameter parameter_P_TIMEPATTERN = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_P_FROMDATETIME = null;
    private JRFillParameter parameter_P_REFERENCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_CP_CURRENCY_EXP = null;
    private JRFillParameter parameter_P_TODATE_TIMESTAMP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_P_CURRENCY = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_P_RECEIVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_P_SQLSERVERROWNUMCONDITION = null;
    private JRFillParameter parameter_P_DATEPATTERN = null;
    private JRFillParameter parameter_P_MESSAGETYPE = null;
    private JRFillParameter parameter_P_AMOUNT = null;
    private JRFillParameter parameter_P_FORMAT = null;
    private JRFillParameter parameter_P_TODATETIME = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_INST_RECEIVER_X1 = null;
    private JRFillField field_MESG_TRN_REF = null;
    private JRFillField field_APPE_SESSION_NBR = null;
    private JRFillField field_APPE_SEQUENCE_NBR = null;
    private JRFillField field_MESG_TYPE = null;
    private JRFillField field_X_FIN_VALUE_DATE = null;
    private JRFillField field_X_FIN_CCY = null;
    private JRFillField field_MESG_CREA_DATE_TIME = null;
    private JRFillField field_MESG_SUB_FORMAT = null;
    private JRFillField field_APPE_NAK_REASON = null;
    private JRFillField field_APPE_NACK_STATUS = null;
    private JRFillField field_X_FIN_AMOUNT = null;
    private JRFillField field_MESG_CREA_OPER_NICKNAME = null;
    private JRFillField field_MESG_SENDER_X1 = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_receiverGroup_COUNT = null;
    private JRFillVariable variable_msgType_group_COUNT = null;
    private JRFillVariable variable_currencyGroup_COUNT = null;
    private JRFillVariable variable_creationDate_group_COUNT = null;
    private JRFillVariable variable_totalCurrency = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_P_SENDER = (JRFillParameter)pm.get("P_SENDER");
        parameter_P_DBPREFIX = (JRFillParameter)pm.get("P_DBPREFIX");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_P_DATETIMEPATTERN = (JRFillParameter)pm.get("P_DATETIMEPATTERN");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_CP_MESG_TRN_REF = (JRFillParameter)pm.get("CP_MESG_TRN_REF");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_CP_AMOUNT_EXP = (JRFillParameter)pm.get("CP_AMOUNT_EXP");
        parameter_P_ORACLEROWNUMCONDITION = (JRFillParameter)pm.get("P_ORACLEROWNUMCONDITION");
        parameter_P_TIMEPATTERN = (JRFillParameter)pm.get("P_TIMEPATTERN");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_P_FROMDATETIME = (JRFillParameter)pm.get("P_FROMDATETIME");
        parameter_P_REFERENCE = (JRFillParameter)pm.get("P_REFERENCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_CP_CURRENCY_EXP = (JRFillParameter)pm.get("CP_CURRENCY_EXP");
        parameter_P_TODATE_TIMESTAMP = (JRFillParameter)pm.get("P_TODATE_TIMESTAMP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_P_CURRENCY = (JRFillParameter)pm.get("P_CURRENCY");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_P_RECEIVER = (JRFillParameter)pm.get("P_RECEIVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_P_SQLSERVERROWNUMCONDITION = (JRFillParameter)pm.get("P_SQLSERVERROWNUMCONDITION");
        parameter_P_DATEPATTERN = (JRFillParameter)pm.get("P_DATEPATTERN");
        parameter_P_MESSAGETYPE = (JRFillParameter)pm.get("P_MESSAGETYPE");
        parameter_P_AMOUNT = (JRFillParameter)pm.get("P_AMOUNT");
        parameter_P_FORMAT = (JRFillParameter)pm.get("P_FORMAT");
        parameter_P_TODATETIME = (JRFillParameter)pm.get("P_TODATETIME");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_INST_RECEIVER_X1 = (JRFillField)fm.get("INST_RECEIVER_X1");
        field_MESG_TRN_REF = (JRFillField)fm.get("MESG_TRN_REF");
        field_APPE_SESSION_NBR = (JRFillField)fm.get("APPE_SESSION_NBR");
        field_APPE_SEQUENCE_NBR = (JRFillField)fm.get("APPE_SEQUENCE_NBR");
        field_MESG_TYPE = (JRFillField)fm.get("MESG_TYPE");
        field_X_FIN_VALUE_DATE = (JRFillField)fm.get("X_FIN_VALUE_DATE");
        field_X_FIN_CCY = (JRFillField)fm.get("X_FIN_CCY");
        field_MESG_CREA_DATE_TIME = (JRFillField)fm.get("MESG_CREA_DATE_TIME");
        field_MESG_SUB_FORMAT = (JRFillField)fm.get("MESG_SUB_FORMAT");
        field_APPE_NAK_REASON = (JRFillField)fm.get("APPE_NAK_REASON");
        field_APPE_NACK_STATUS = (JRFillField)fm.get("APPE_NACK_STATUS");
        field_X_FIN_AMOUNT = (JRFillField)fm.get("X_FIN_AMOUNT");
        field_MESG_CREA_OPER_NICKNAME = (JRFillField)fm.get("MESG_CREA_OPER_NICKNAME");
        field_MESG_SENDER_X1 = (JRFillField)fm.get("MESG_SENDER_X1");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_receiverGroup_COUNT = (JRFillVariable)vm.get("receiverGroup_COUNT");
        variable_msgType_group_COUNT = (JRFillVariable)vm.get("msgType_group_COUNT");
        variable_currencyGroup_COUNT = (JRFillVariable)vm.get("currencyGroup_COUNT");
        variable_creationDate_group_COUNT = (JRFillVariable)vm.get("creationDate_group_COUNT");
        variable_totalCurrency = (JRFillVariable)vm.get("totalCurrency");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "reportStyle.jrtx"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.util.Date(90,0,1,0,0,0); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.util.Date(190,0,1,0,0,0); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = "%"; //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = "%"; //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = "%"; //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = "%"; //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = "%"; //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "%"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new BigDecimal(0.0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ""; //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ""; //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ""; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "MM/dd/yyyy"; //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "hh:mm:ss a"; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "MM/dd/yyyy hh:mm:ss a"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.sql.Timestamp(((java.util.Date)parameter_P_TODATETIME.getValue()).getTime()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "%".equals(((java.lang.String)parameter_P_CURRENCY.getValue()))?("( RepFinMsgView.X_FIN_CCY IS NULL OR RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "')") //$JR_EXPR_ID=17$
: (" RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "'"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).intValue() == 0?("( RepFinMsgView.X_FIN_AMOUNT IS NULL OR RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()) + ")") //$JR_EXPR_ID=18$
: (" RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ( //$JR_EXPR_ID=19$
    (((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()) != null && !"".equals(((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()).trim())) //$JR_EXPR_ID=19$
    ? //$JR_EXPR_ID=19$
    "UPPER(NVL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
    : //$JR_EXPR_ID=19$
    "UPPER(ISNULL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)field_X_FIN_AMOUNT.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TIME"); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TRN_REFERENCE"); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("IO"); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER"); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("OPERATOR"); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("VALUE_DATE"); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT"); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SN_SEQ"); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("NACK"); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_COUNT")+":"; //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = String.valueOf(((java.lang.Integer)variable_currencyGroup_COUNT.getValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TOTAL_CURRENCY")+ " " + //$JR_EXPR_ID=57$
(((java.lang.String)field_X_FIN_CCY.getValue()) != null?((java.lang.String)field_X_FIN_CCY.getValue()):"") //$JR_EXPR_ID=57$
+ " "+":"; //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.math.BigDecimal)variable_totalCurrency.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (new SimpleDateFormat("MM/dd/yyyy")).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CREATION_DATE"); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AUDIT_ANALYSIS_REPORT_NAME"); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER")+":"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_P_SENDER.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = "logo.png"; //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("FIN_MSG_SUB_RECEIVER_MSG_TYPE_AND_CURR"); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_P_RECEIVER.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("REFERENCE")+":"; //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_P_REFERENCE.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_P_MESSAGETYPE.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_P_CURRENCY.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT")+":"; //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "%" : ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "" : "#,##0.00"; //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SUBFORMAT")+":"; //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_P_FORMAT.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_FROMDATETIME.getValue())) //$JR_EXPR_ID=80$
+ "-" + //$JR_EXPR_ID=80$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_TODATETIME.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "CREATION_DATE" )+":"; //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getValue()) % 2 == 0; //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_TIMEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)field_MESG_TRN_REF.getValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_X_FIN_VALUE_DATE.getValue()).getTime())); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = String.valueOf(((java.math.BigDecimal)field_X_FIN_AMOUNT.getValue()).doubleValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)field_MESG_SUB_FORMAT.getValue()).equals("INPUT")?"I":"O"; //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.math.BigDecimal)field_APPE_SESSION_NBR.getValue()).toString()+"/"+((java.math.BigDecimal)field_APPE_SEQUENCE_NBR.getValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==0?"ACK": //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==1?((java.lang.String)field_APPE_NAK_REASON.getValue()): //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==3?"---":((java.lang.String)field_APPE_NAK_REASON.getValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)field_MESG_CREA_OPER_NICKNAME.getValue())+" "; //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)field_MESG_SENDER_X1.getValue()) + " "; //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "PRINTED" ) + " " + //$JR_EXPR_ID=92$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(new java.util.Date()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+" of"; //$JR_EXPR_ID=94$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "reportStyle.jrtx"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.util.Date(90,0,1,0,0,0); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.util.Date(190,0,1,0,0,0); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = "%"; //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = "%"; //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = "%"; //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = "%"; //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = "%"; //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "%"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new BigDecimal(0.0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ""; //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ""; //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ""; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "MM/dd/yyyy"; //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "hh:mm:ss a"; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "MM/dd/yyyy hh:mm:ss a"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.sql.Timestamp(((java.util.Date)parameter_P_TODATETIME.getValue()).getTime()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "%".equals(((java.lang.String)parameter_P_CURRENCY.getValue()))?("( RepFinMsgView.X_FIN_CCY IS NULL OR RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "')") //$JR_EXPR_ID=17$
: (" RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "'"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).intValue() == 0?("( RepFinMsgView.X_FIN_AMOUNT IS NULL OR RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()) + ")") //$JR_EXPR_ID=18$
: (" RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ( //$JR_EXPR_ID=19$
    (((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()) != null && !"".equals(((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()).trim())) //$JR_EXPR_ID=19$
    ? //$JR_EXPR_ID=19$
    "UPPER(NVL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
    : //$JR_EXPR_ID=19$
    "UPPER(ISNULL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)field_X_FIN_AMOUNT.getOldValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getOldValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getOldValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getOldValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getOldValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getOldValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TIME"); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TRN_REFERENCE"); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("IO"); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER"); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("OPERATOR"); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("VALUE_DATE"); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT"); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SN_SEQ"); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("NACK"); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getOldValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_COUNT")+":"; //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = String.valueOf(((java.lang.Integer)variable_currencyGroup_COUNT.getOldValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TOTAL_CURRENCY")+ " " + //$JR_EXPR_ID=57$
(((java.lang.String)field_X_FIN_CCY.getOldValue()) != null?((java.lang.String)field_X_FIN_CCY.getOldValue()):"") //$JR_EXPR_ID=57$
+ " "+":"; //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.math.BigDecimal)variable_totalCurrency.getOldValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (new SimpleDateFormat("MM/dd/yyyy")).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getOldValue()).getTime())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getOldValue()).getTime())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CREATION_DATE"); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AUDIT_ANALYSIS_REPORT_NAME"); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER")+":"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_P_SENDER.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = "logo.png"; //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("FIN_MSG_SUB_RECEIVER_MSG_TYPE_AND_CURR"); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_P_RECEIVER.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("REFERENCE")+":"; //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_P_REFERENCE.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_P_MESSAGETYPE.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_P_CURRENCY.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT")+":"; //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "%" : ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "" : "#,##0.00"; //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SUBFORMAT")+":"; //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_P_FORMAT.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_FROMDATETIME.getValue())) //$JR_EXPR_ID=80$
+ "-" + //$JR_EXPR_ID=80$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_TODATETIME.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "CREATION_DATE" )+":"; //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getOldValue()) % 2 == 0; //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_TIMEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getOldValue()).getTime())); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)field_MESG_TRN_REF.getOldValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_X_FIN_VALUE_DATE.getOldValue()).getTime())); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = String.valueOf(((java.math.BigDecimal)field_X_FIN_AMOUNT.getOldValue()).doubleValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)field_MESG_SUB_FORMAT.getOldValue()).equals("INPUT")?"I":"O"; //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.math.BigDecimal)field_APPE_SESSION_NBR.getOldValue()).toString()+"/"+((java.math.BigDecimal)field_APPE_SEQUENCE_NBR.getOldValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.math.BigDecimal)field_APPE_NACK_STATUS.getOldValue()).intValue()==0?"ACK": //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getOldValue()).intValue()==1?((java.lang.String)field_APPE_NAK_REASON.getOldValue()): //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getOldValue()).intValue()==3?"---":((java.lang.String)field_APPE_NAK_REASON.getOldValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)field_MESG_CREA_OPER_NICKNAME.getOldValue())+" "; //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)field_MESG_SENDER_X1.getOldValue()) + " "; //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "PRINTED" ) + " " + //$JR_EXPR_ID=92$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(new java.util.Date()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+" of"; //$JR_EXPR_ID=94$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "reportStyle.jrtx"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.util.Date(90,0,1,0,0,0); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.util.Date(190,0,1,0,0,0); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = "%"; //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = "%"; //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = "%"; //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = "%"; //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = "%"; //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "%"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new BigDecimal(0.0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ""; //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ""; //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ""; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "MM/dd/yyyy"; //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "hh:mm:ss a"; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "MM/dd/yyyy hh:mm:ss a"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.sql.Timestamp(((java.util.Date)parameter_P_TODATETIME.getValue()).getTime()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "%".equals(((java.lang.String)parameter_P_CURRENCY.getValue()))?("( RepFinMsgView.X_FIN_CCY IS NULL OR RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "')") //$JR_EXPR_ID=17$
: (" RepFinMsgView.X_FIN_CCY LIKE '" + ((java.lang.String)parameter_P_CURRENCY.getValue()) + "'"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).intValue() == 0?("( RepFinMsgView.X_FIN_AMOUNT IS NULL OR RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()) + ")") //$JR_EXPR_ID=18$
: (" RepFinMsgView.X_FIN_AMOUNT >= " + ((java.math.BigDecimal)parameter_P_AMOUNT.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ( //$JR_EXPR_ID=19$
    (((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()) != null && !"".equals(((java.lang.String)parameter_P_ORACLEROWNUMCONDITION.getValue()).trim())) //$JR_EXPR_ID=19$
    ? //$JR_EXPR_ID=19$
    "UPPER(NVL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
    : //$JR_EXPR_ID=19$
    "UPPER(ISNULL(repFinMsgView.MESG_TRN_REF, ''))" //$JR_EXPR_ID=19$
); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)field_X_FIN_AMOUNT.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_MESG_TYPE.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_X_FIN_CCY.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TIME"); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TRN_REFERENCE"); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("IO"); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER"); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("OPERATOR"); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("VALUE_DATE"); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT"); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SN_SEQ"); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("NACK"); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_INST_RECEIVER_X1.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_COUNT")+":"; //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = String.valueOf(((java.lang.Integer)variable_currencyGroup_COUNT.getEstimatedValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("TOTAL_CURRENCY")+ " " + //$JR_EXPR_ID=57$
(((java.lang.String)field_X_FIN_CCY.getValue()) != null?((java.lang.String)field_X_FIN_CCY.getValue()):"") //$JR_EXPR_ID=57$
+ " "+":"; //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.math.BigDecimal)variable_totalCurrency.getEstimatedValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (new SimpleDateFormat("MM/dd/yyyy")).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CREATION_DATE"); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AUDIT_ANALYSIS_REPORT_NAME"); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SENDER")+":"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_P_SENDER.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = "logo.png"; //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("FIN_MSG_SUB_RECEIVER_MSG_TYPE_AND_CURR"); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("RECEIVER")+":"; //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_P_RECEIVER.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("REFERENCE")+":"; //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_P_REFERENCE.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("MESSAGE_TYPE")+":"; //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_P_MESSAGETYPE.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("CURRENCY")+":"; //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_P_CURRENCY.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("AMOUNT")+":"; //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "%" : ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.math.BigDecimal)parameter_P_AMOUNT.getValue()).toString().equals("0") ? "" : "#,##0.00"; //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString("SUBFORMAT")+":"; //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_P_FORMAT.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_FROMDATETIME.getValue())) //$JR_EXPR_ID=80$
+ "-" + //$JR_EXPR_ID=80$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(((java.util.Date)parameter_P_TODATETIME.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "CREATION_DATE" )+":"; //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()) % 2 == 0; //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_TIMEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_MESG_CREA_DATE_TIME.getValue()).getTime())); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)field_MESG_TRN_REF.getValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (new SimpleDateFormat(((java.lang.String)parameter_P_DATEPATTERN.getValue()))).format(new java.util.Date(((java.sql.Timestamp)field_X_FIN_VALUE_DATE.getValue()).getTime())); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = String.valueOf(((java.math.BigDecimal)field_X_FIN_AMOUNT.getValue()).doubleValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)field_MESG_SUB_FORMAT.getValue()).equals("INPUT")?"I":"O"; //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.math.BigDecimal)field_APPE_SESSION_NBR.getValue()).toString()+"/"+((java.math.BigDecimal)field_APPE_SEQUENCE_NBR.getValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==0?"ACK": //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==1?((java.lang.String)field_APPE_NAK_REASON.getValue()): //$JR_EXPR_ID=89$
((java.math.BigDecimal)field_APPE_NACK_STATUS.getValue()).intValue()==3?"---":((java.lang.String)field_APPE_NAK_REASON.getValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)field_MESG_CREA_OPER_NICKNAME.getValue())+" "; //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)field_MESG_SENDER_X1.getValue()) + " "; //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()).getString( "PRINTED" ) + " " + //$JR_EXPR_ID=92$
(new SimpleDateFormat(((java.lang.String)parameter_P_DATETIMEPATTERN.getValue()))).format(new java.util.Date()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+" of"; //$JR_EXPR_ID=94$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
